### ISSUE TITLE
Did this get finished?

### ISSUE THREAD

**Issue by PrimeLens** [willbuckingham/node-rest-mysql#1]
Not a bug but couldn't find a conversation attached to this project to ask my question.
Just wondering on the status, is this in a finished state?

**Comment by willbuckingham** [comment]
State of this project is that it is a functional prototype.  As an end user of this, you would have to modify your routes and mysql commands/logic to be inline with your needs.

There are also future considerations for this project as noted in the readme:
https://github.com/willbuckingham/node-rest-mysql#todo

**Comment by PrimeLens** [comment]
Thanks Will
